# Generated by Django 6.0 on 2025-12-06 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.TextField(blank=True, help_text='Plain text document content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('web', 'Web'), ('audio', 'Audio')], default='text', max_length=10)),
                ('raw_text', models.TextField(help_text='Source text (paste / web summary / transcription)')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Optional metadata (url, filename, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='writerapp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
